index:
    path: /
    controller: App\Controller\AppController::index

authenticate:
    path: /authenticate
    controller: App\Controller\AppController::authenticate

logout:
    path: /logout
    methods: GET

save_profile:
    path:       /profile
    controller: App\Controller\AppController::saveProfile
    methods:    POST